neutron --os-username=admin --os-password={{ ADMIN_PASS }} --os-tenant-name=admin --os-auth-url=http://controller:35357/v2.0 net-create ext-net --shared --router:external=True
neutron --os-username=admin --os-password={{ ADMIN_PASS }} --os-tenant-name=admin --os-auth-url=http://controller:35357/v2.0 subnet-create ext-net --name ext-subnet --allocation-pool start={{ FLOATING_IP_START }},end={{ FLOATING_IP_END}} --disable-dhcp --gateway {{EXTERNAL_NETWORK_GATEWAY}} {{EXTERNAL_NETWORK_CIDR}}

neutron --os-username=demo --os-password={{ DEMO_PASS }} net-create demo-net
neutron --os-username=demo --os-password={{ DEMO_PASS }} subnet-create demo-net --name demo-subnet --gateway {{ TENANT_NETWORK_GATEWAY }} {{ TENANT_NETWORK_CIDR }}

neutron --os-username=demo --os-password={{ DEMO_PASS }} router-create demo-router
neutron --os-username=demo --os-password={{ DEMO_PASS }} router-interface-add demo-router demo-subnet
neutron --os-username=demo --os-password={{ DEMO_PASS }} router-gateway-set demo-router ext-net
