# create an administrative user

keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 user-create --name=admin --pass={{ ADMIN_PASS }} --email=admin@admin.com
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 role-create --name=admin
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 tenant-create --name=admin --description="Admin Tenant"
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 user-role-add --user=admin --tenant=admin --role=admin
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 user-role-add --user=admin --role=_member_ --tenant=admin

# create a normal user

keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 user-create --name=demo --pass={{ DEMO_PASS }} --email=DEMO_EMAIL
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 tenant-create --name=demo --description="Demo Tenant"
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 user-role-add --user=demo --role=_member_ --tenant=demo

# create a service tenant
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 tenant-create --name=service --description="Service Tenant"

# regist keystone
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 service-create --name=keystone --type=identity --description="OpenStack Identity"
keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 endpoint-create --service_id=$(keystone --token={{ ADMIN_TOKEN }} --endpoint=http://controller:35357/v2.0 service-list | awk '/ identity / {print $2}') --publicurl=http://controller:5000/v2.0 --internalurl=http://controller:5000/v2.0 --adminurl=http://controller:35357/v2.0
